version: 0.2

phases: 
  pre_build: 
    commands:
      - npm install 
  build:
    commands: 
      -npm start 
    
  artifacts: 
    files:
      - '**/*'
    discard-paths: no
    base-directory: ./